name: Build Symplex App for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List directory contents
        run: dir
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "DejaVuSans.ttf;." --log-level DEBUG symplex.py
      - name: Check if executable exists
        run: |
          if exist dist\symplex.exe (echo Executable created successfully) else (echo Error: Executable not found && exit 1)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symplex-app-windows
          path: dist/symplex.exe
          retention-days: 7
