name: Build Symplex App for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reportlab pyinstaller

      - name: List directory contents (debug)
        run: dir

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "DejaVuSans.ttf;." symplex.py

      - name: Verify executable exists (PowerShell)
        run: |
          if (Test-Path -Path "dist\symplex.exe") {
            Write-Output "✅ Executable created successfully"
          } else {
            Write-Output "❌ Error: Executable not found!"
            exit 1
          }
        shell: pwsh  # Явно указываем PowerShell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symplex-app-windows
          path: dist/symplex.exe
          retention-days: 7
